FROM harmonydata/harmonyapi:20230708185427_4f28802

RUN apt update && apt install -y nodejs npm

RUN python harmony/src/harmony/util/model_downloader.py 

RUN git clone https://github.com/harmonydata/harmonydata.github.io

# Make sure Harmony front end points to local Harmony back end
RUN sed -i s#https://api.harmonydata.org#http://localhost:8000# */*/*/*js

WORKDIR /backend/harmonydata.github.io
RUN npm install
WORKDIR /backend

EXPOSE 8000
EXPOSE 3000

CMD ["bash", "start_harmony_local.sh"]
