FROM harmonydata/harmonyapi:latest

RUN apt update && apt install -y default-jre tesseract-ocr

RUN python -c 'from tika import parser; parser.from_buffer("abc", xmlContent=True)'

ENV COMMIT_ID=$COMMIT_ID

CMD ["uvicorn", "main:app_fastapi", "--host", "0.0.0.0", "--port", "80"]

