FROM harmonydata/harmonyapi:latest

RUN apt update && apt install -y nodejs npm

RUN python harmony/src/harmony/util/model_downloader.py 

RUN git clone https://github.com/harmonydata/harmonydata.github.io

ENV REACT_APP_API_URL=http://localhost:8000/
# Make sure Harmony front end points to local Harmony back end

WORKDIR /backend/harmonydata.github.io
RUN npm install
WORKDIR /backend

EXPOSE 8000
EXPOSE 3000

CMD ["bash", "start_harmony_local.sh"]
