FROM harmonydata/harmonyapi:latest

RUN apt update && apt install -y default-jre

RUN python -c 'from tika import parser; parser.from_buffer("abc", xmlContent=True)'

CMD ["uvicorn", "main:app_fastapi", "--host", "0.0.0.0", "--port", "80"]

